export default {
  SPLASH_SCREEN_IMAGE: require('../../assets/images/pexels-stas-knop-1261578.jpg'),
  MUSIC_TONE_IMAGE: require('../../assets/images/tone.png'),
  MUSIC_NOTE_IMAGE: require('../../assets/images/music-player.png'),
  IMAGE_ONE: require('../../assets/images/pexels-daniel-reche-3721941.jpg'),
  IMAGE_TWO: require('../../assets/images/pexels-dmitry-demidov-3784566.jpg'),
  IMAGE_THREE: require('../../assets/images/pexels-mark-angelo-sampan-1587927.jpg'),
  IMAGE_FOUR: require('../../assets/images/pexels-moose-photos-1037992.jpg'),
  IMAGE_FIVE: require('../../assets/images/pexels-pixabay-164879.jpg'),
  IMAGE_SIX: require('../../assets/images/pexels-pixabay-417458.jpg'),
  IMAGE_SEVEN: require('../../assets/images/pexels-porapak-apichodilok-346728.jpg'),
  IMAGE_EIGHT: require('../../assets/images/pexels-stas-knop-1261578.jpg'),
  IMAGE_NINE: require('../../assets/images/pexels-thibault-trillet-167491.jpg'),
  IMAGE_TEN: require('../../assets/images/pexels-vishnu-r-nair-1105666.jpg'),
};
